services:
  db:
    image: postgres:17-alpine
    container_name: fxdxp-db
    restart: always
    networks:
      - private_net
    secrets:
      - db_user
      - db_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_DB: fxdxp_db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "sh", "-c", "pg_isready -U $$(cat /run/secrets/db_user) -d fxdxp_db"]
      interval: 10s
      retries: 5
      timeout: 5s

  fxdxp-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fxdxp-app
    networks:
      - private_net
      - public_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      retries: 3
      timeout: 5s
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    networks:
      - public_net
    depends_on:
      fxdxp-app:
        condition: service_healthy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  public_net:
    driver: bridge

  private_net:
    driver: bridge
    internal: true

volumes:
  db_data:

secrets:
  db_user:
    file: ./secrets/db_user
  db_password:
    file: ./secrets/db_password