http {
    upstream fxdxp-app {
        server fxdxp-app:5000;
    }

    server {
        listen 80;
        # Add 443 rule when we'll have TLS Certificate

        server_name localhost; # Change with domain name

        location / {
            proxy_pass http://fxdxp-app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # To remove nginx's forced anonimity
        }
    }
}